name: p38
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.9.9
  - libedit=3.1.20230828
  - libffi=3.2.1
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=24.2
  - pthread-stubs=0.3
  - python=3.8.0
  - readline=7.0
  - setuptools=75.1.0
  - sqlite=3.33.0
  - tk=8.6.15
  - wheel=0.44.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - anyio==4.5.2
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==25.3.0
      - babel==2.17.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.5
      - bleach==6.1.0
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - comm==0.2.3
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.1.4
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.13.1
      - fonttools==4.57.0
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - future==1.0.0
      - h11==0.16.0
      - h5py==3.11.0
      - himalaya==0.4.8
      - html5lib==1.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - infomap==2.8.0
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - jpype1==1.6.0
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - konlpy==0.6.0
      - lazy-loader==0.4
      - looseversion==1.3.0
      - lxml==6.0.1
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mda-xdrlib==0.2.0
      - mistune==3.1.4
      - mne==1.6.1
      - mpmath==1.3.0
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - neo==0.13.3
      - nest-asyncio==1.6.0
      - networkx==3.0
      - nibabel==5.2.1
      - nilearn==0.10.4
      - nltools==0.5.1
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numexpr==2.8.6
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - openpyxl==3.1.5
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.0.3
      - pandas-flavor==0.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - patsy==1.0.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pingouin==0.5.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - pooch==1.8.2
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycortex==1.2.11
      - pycparser==2.23
      - pygments==2.19.2
      - pynv==0.3
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - quantities==0.15.0
      - referencing==0.35.1
      - requests==2.32.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.1
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.38.0
      - shapely==2.0.7
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - statsmodels==0.14.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.2.1
      - tomli==2.2.1
      - torch==2.4.1+cu118
      - torchaudio==2.4.1+cu118
      - torchvision==0.19.1+cu118
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.0.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
      - xarray==2023.1.0
      - zipp==3.20.2
prefix: /home/dasom/.conda/envs/p38
